/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete account
         * @description Deletes the account with all of its data (F-17) and ends the session. Cannot be undone.
         */
        delete: operations["authDeleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Checks e-mail and password and sets the session cookie on success. Wrong credentials and unknown addresses get the same 401 response in the same time. When too many logins and registrations are already being checked, returns 503 at once with a Retry-After header; retry a few seconds later.
         */
        post: operations["authLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Revokes the session on the server and clears the cookie. Idempotent: also works without a cookie or with one that is no longer valid.
         */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out everywhere
         * @description Revokes every session of the account on every device, this one included, and clears the cookie. For a lost device or a cookie that may have been stolen.
         */
        post: operations["authLogoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current account
         * @description Returns the account of the current session. The frontend calls it on every page request to determine the login state.
         */
        get: operations["authMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create account
         * @description Creates an account and logs it in right away: the response sets the session cookie. Returns 403 while registration is closed (`REGISTRATION_ENABLED`). The e-mail address is stored lowercased; an address that is already registered returns 409. When too many logins and registrations are already being checked, returns 503 at once with a Retry-After header; retry a few seconds later.
         */
        post: operations["authRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List gift ideas
         * @description Returns the gift ideas of the current account, newest first, one page at a time. `total` counts all gift ideas of the account.
         */
        get: operations["listGifts"];
        put?: never;
        /**
         * Create gift idea
         * @description Creates a gift idea for the current account. Only the title is required, so an idea can be captured in one step: empty optional fields are stored as null, `currency` defaults to EUR and `category` to `other`. The creation time is set by the server. `person_ids` and `occasion_ids` link the idea to people and occasions of the account; an ID of another account returns 404, like a missing one, and nothing is saved.
         */
        post: operations["createGift"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gifts/{gift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show gift idea
         * @description Returns one gift idea of the current account. A gift idea of another account returns 404, like a missing one.
         */
        get: operations["getGift"];
        /**
         * Update gift idea
         * @description Replaces all fields of the gift idea, including its links: a field left out is reset to null, its default or an empty list. The frontend sends the whole form. `person_ids` and `occasion_ids` link the idea to people and occasions of the account; an ID of another account returns 404, like a missing one, and nothing is saved. A gift idea of another account returns 404, like a missing one.
         */
        put: operations["updateGift"];
        post?: never;
        /**
         * Delete gift idea
         * @description Deletes the gift idea. Cannot be undone. A gift idea of another account returns 404, like a missing one.
         */
        delete: operations["deleteGift"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Process is up
         * @description Answers as soon as the process accepts requests; does not touch the database. Target of the container healthcheck.
         */
        get: operations["healthLive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Database reachable
         * @description Runs `SELECT 1`. Without a database it returns `status: degraded` with HTTP 200, so that Traefik keeps the container in rotation while it is still starting.
         */
        get: operations["healthReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occasion-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List occasion types
         * @description Returns the system-wide types Geburtstag and Weihnachten followed by the account's own types. System-wide types are read-only: there is no endpoint to change or delete them.
         */
        get: operations["listOccasionTypes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occasion-types/{occasion_type_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show occasion type
         * @description Returns one system-wide type or one of the account's own types. A type of another account returns 404.
         */
        get: operations["getOccasionType"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occasions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List occasions
         * @description Returns the occasions of the current account, sorted by date, one page at a time. `total` counts all occasions of the account.
         */
        get: operations["listOccasions"];
        put?: never;
        /**
         * Create occasion
         * @description Creates a one-off or yearly occasion for the current account. `occasion_type_id` must be a system-wide type or one of the account; otherwise 404. `person_ids` links the occasion to people of the account; an ID of another account returns 404, like a missing one, and nothing is saved.
         */
        post: operations["createOccasion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occasions/{occasion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show occasion
         * @description Returns one occasion of the current account. An occasion of another account returns 404, like a missing one.
         */
        get: operations["getOccasion"];
        /**
         * Update occasion
         * @description Replaces all fields of the occasion, including its links: a field left out is reset to its default or an empty list. The frontend sends the whole form. An occasion of another account returns 404, like a missing one. `occasion_type_id` must be a system-wide type or one of the account; otherwise 404. `person_ids` links the occasion to people of the account; an ID of another account returns 404, like a missing one, and nothing is saved.
         */
        put: operations["updateOccasion"];
        post?: never;
        /**
         * Delete occasion
         * @description Deletes the occasion. Cannot be undone. An occasion of another account returns 404, like a missing one.
         */
        delete: operations["deleteOccasion"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List people
         * @description Returns the people of the current account, sorted by name (case-insensitive), one page at a time. `total` counts all people of the account.
         */
        get: operations["listPeople"];
        put?: never;
        /**
         * Create person
         * @description Creates a person for the current account. Only the name is required; empty optional fields are stored as null.
         */
        post: operations["createPerson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/people/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Show person
         * @description Returns one person of the current account. A person of another account returns 404, like a missing one.
         */
        get: operations["getPerson"];
        /**
         * Update person
         * @description Replaces all fields of the person: a field left out is reset to null. The frontend sends the whole form. A person of another account returns 404, like a missing one.
         */
        put: operations["updatePerson"];
        post?: never;
        /**
         * Delete person
         * @description Deletes the person. Cannot be undone. A person of another account returns 404, like a missing one.
         */
        delete: operations["deletePerson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * GiftCategory
         * @description Kind of gift; the aggregated feature for suggestions (F-16).
         * @enum {string}
         */
        GiftCategory: "books" | "games" | "experience" | "clothing" | "tech" | "food" | "home" | "voucher" | "other";
        /**
         * GiftIn
         * @description Data of a gift idea; used for create and for full update (PUT).
         */
        GiftIn: {
            /**
             * @description Kind of gift, used for suggestions (F-16). `other` when not chosen.
             * @default other
             * @example tech
             */
            category: components["schemas"]["GiftCategory"];
            /**
             * Currency
             * @description ISO 4217 code of the price range currency, three capital letters.
             * @default EUR
             * @example EUR
             */
            currency: string;
            /**
             * Description
             * @description Free-text description, up to 2000 characters. Empty means not set.
             * @example Technik, für IT-Begeisterte
             */
            description?: string | null;
            /**
             * Occasion Ids
             * @description IDs of the account's occasions the idea is meant for, up to 100. Replaces the current links; empty or left out means none.
             * @example [
             *       "0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a72"
             *     ]
             */
            occasion_ids?: string[];
            /**
             * Person Ids
             * @description IDs of the account's people the idea is meant for (possible recipients), up to 100. Replaces the current links; empty or left out means none.
             * @example [
             *       "0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a71"
             *     ]
             */
            person_ids?: string[];
            /**
             * Price From
             * @description Lower end of the price range in `currency`, at most 2 decimal places.
             * @example 10.00
             */
            price_from?: number | string | null;
            /**
             * Price To
             * @description Upper end of the price range in `currency`, at most 2 decimal places. Must not be below `price_from`.
             * @example 100.00
             */
            price_to?: number | string | null;
            /**
             * Title
             * @description Title, 1 to 200 characters. The only required field.
             * @example Raspberry Pi
             */
            title: string;
        };
        /**
         * GiftOut
         * @description A gift idea as the frontend sees it.
         */
        GiftOut: {
            /**
             * @description Kind of gift.
             * @example tech
             */
            category: components["schemas"]["GiftCategory"];
            /**
             * Created At
             * Format: date-time
             * @description Creation time (UTC), set by the server.
             * @example 2026-10-04T09:30:00Z
             */
            created_at: string;
            /**
             * Currency
             * @description ISO 4217 currency code.
             * @example EUR
             */
            currency: string;
            /**
             * Description
             * @description Free-text description, or null.
             * @example Technik, für IT-Begeisterte
             */
            description: string | null;
            /**
             * Id
             * Format: uuid
             * @description Gift idea ID (UUIDv7).
             * @example 0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a70
             */
            id: string;
            /**
             * Occasions
             * @description Occasions the idea is meant for, sorted by date.
             * @example [
             *       {
             *         "id": "0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a72",
             *         "name": "Weihnachten"
             *       }
             *     ]
             */
            occasions: components["schemas"]["LinkedOccasion"][];
            /**
             * People
             * @description People the idea is meant for (possible recipients), sorted by name.
             * @example [
             *       {
             *         "id": "0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a71",
             *         "name": "Lena"
             *       }
             *     ]
             */
            people: components["schemas"]["LinkedPerson"][];
            /**
             * Price From
             * @description Lower end of the price range in `currency`, as a string, or null.
             * @example 10.00
             */
            price_from: string | null;
            /**
             * Price To
             * @description Upper end of the price range in `currency`, as a string, or null.
             * @example 100.00
             */
            price_to: string | null;
            /**
             * Title
             * @description Title.
             * @example Raspberry Pi
             */
            title: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthOut
         * @description State of the service and its database connection.
         */
        HealthOut: {
            /** Database */
            database: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
        };
        /**
         * LinkedOccasion
         * @description An occasion a gift idea is linked to.
         */
        LinkedOccasion: {
            /**
             * Id
             * Format: uuid
             * @description Occasion ID (UUIDv7).
             * @example 0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a72
             */
            id: string;
            /**
             * Name
             * @description Title.
             * @example Weihnachten
             */
            name: string;
        };
        /**
         * LinkedPerson
         * @description A person a gift idea or an occasion is linked to.
         */
        LinkedPerson: {
            /**
             * Id
             * Format: uuid
             * @description Person ID (UUIDv7).
             * @example 0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a71
             */
            id: string;
            /**
             * Name
             * @description Name.
             * @example Lena
             */
            name: string;
        };
        /**
         * LoginIn
         * @description Login credentials.
         */
        LoginIn: {
            /**
             * Email
             * Format: email
             * @description Login name.
             * @example anna@example.org
             */
            email: string;
            /**
             * Password
             * @description Password.
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * OccasionIn
         * @description Data of an occasion; used for create and for full update (PUT).
         */
        OccasionIn: {
            /**
             * Date
             * Format: date
             * @description Date as a plain date (YYYY-MM-DD). First occurrence for yearly occasions.
             * @example 2019-06-21
             */
            date: string;
            /**
             * Name
             * @description Title, 1 to 100 characters.
             * @example Hochzeitstag
             */
            name: string;
            /**
             * Occasion Type Id
             * @description Occasion type, a system-wide one or one of the account. Null for an own occasion without a type.
             * @example null
             */
            occasion_type_id?: string | null;
            /**
             * Person Ids
             * @description IDs of the account's people the occasion concerns, up to 100. Replaces the current links; empty or left out means none.
             * @example [
             *       "0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a71"
             *     ]
             */
            person_ids?: string[];
            /**
             * @description `none` for a one-off occasion, `yearly` for every year on the same day.
             * @default none
             * @example yearly
             */
            recurrence: components["schemas"]["Recurrence"];
        };
        /**
         * OccasionOut
         * @description An occasion as the frontend sees it.
         */
        OccasionOut: {
            /**
             * Date
             * Format: date
             * @description Date as a plain date.
             * @example 2019-06-21
             */
            date: string;
            /**
             * Id
             * Format: uuid
             * @description Occasion ID (UUIDv7).
             * @example 01a10a3c-7d2e-7c41-9b0e-3f5a8d2c1e94
             */
            id: string;
            /**
             * Name
             * @description Title.
             * @example Hochzeitstag
             */
            name: string;
            /**
             * Occasion Type Id
             * @description Occasion type, or null.
             * @example null
             */
            occasion_type_id: string | null;
            /**
             * People
             * @description People the occasion concerns, sorted by name.
             * @example [
             *       {
             *         "id": "0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a71",
             *         "name": "Lena"
             *       }
             *     ]
             */
            people: components["schemas"]["LinkedPerson"][];
            /**
             * @description `none` or `yearly`.
             * @example yearly
             */
            recurrence: components["schemas"]["Recurrence"];
        };
        /**
         * OccasionTypeOut
         * @description An occasion type. System-wide types are read-only.
         */
        OccasionTypeOut: {
            /**
             * @description Suggested recurrence for occasions of this type.
             * @example yearly
             */
            default_recurrence: components["schemas"]["Recurrence"];
            /**
             * Id
             * Format: uuid
             * @description Occasion type ID (UUIDv7).
             * @example 01a107a9-211b-7486-a304-d5d673618f5b
             */
            id: string;
            /**
             * Name
             * @description Display name.
             * @example Geburtstag
             */
            name: string;
            /**
             * System
             * @description True for the system-wide types, which nobody can change or delete.
             * @example true
             */
            system: boolean;
        };
        /** Page[GiftOut] */
        Page_GiftOut_: {
            /** Items */
            items: components["schemas"]["GiftOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[OccasionOut] */
        Page_OccasionOut_: {
            /** Items */
            items: components["schemas"]["OccasionOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[OccasionTypeOut] */
        Page_OccasionTypeOut_: {
            /** Items */
            items: components["schemas"]["OccasionTypeOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** Page[PersonOut] */
        Page_PersonOut_: {
            /** Items */
            items: components["schemas"]["PersonOut"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /**
         * PersonIn
         * @description Data of a person; used for create and for full update (PUT).
         */
        PersonIn: {
            /**
             * Birthday
             * @description Birthday as a plain date (YYYY-MM-DD), without time or time zone.
             * @example 1994-03-17
             */
            birthday?: string | null;
            /**
             * Name
             * @description Name, 1 to 100 characters.
             * @example Lena
             */
            name: string;
            /**
             * Notes
             * @description Free-text notes, up to 2000 characters. Empty means not set.
             * @example Mag Bouldern und Kaffee, Kleidergröße M
             */
            notes?: string | null;
            /**
             * Relationship
             * @description Relationship to the person, up to 100 characters. Empty means not set.
             * @example Schwester
             */
            relationship?: string | null;
        };
        /**
         * PersonOut
         * @description A person as the frontend sees it.
         */
        PersonOut: {
            /**
             * Birthday
             * @description Birthday as a plain date, or null.
             * @example 1994-03-17
             */
            birthday: string | null;
            /**
             * Created At
             * Format: date-time
             * @description Creation time (UTC).
             * @example 2026-10-04T09:30:00Z
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             * @description Person ID (UUIDv7).
             * @example 0199a8c2-5e3b-7f10-8a4d-2c6e9b1f3a70
             */
            id: string;
            /**
             * Name
             * @description Name.
             * @example Lena
             */
            name: string;
            /**
             * Notes
             * @description Free-text notes, or null.
             * @example Mag Bouldern und Kaffee, Kleidergröße M
             */
            notes: string | null;
            /**
             * Relationship
             * @description Relationship to the person, or null.
             * @example Schwester
             */
            relationship: string | null;
        };
        /**
         * Problem
         * @description Error body for every status outside 2xx (RFC 9457).
         */
        Problem: {
            /** Detail */
            detail: string;
            /** Errors */
            errors?: components["schemas"]["ValidationIssue"][] | null;
            /** Status */
            status: number;
            /** Title */
            title: string;
            /**
             * Type
             * @default about:blank
             */
            type: string;
        };
        /**
         * Recurrence
         * @description How often an occasion repeats.
         * @enum {string}
         */
        Recurrence: "none" | "yearly";
        /**
         * RegisterIn
         * @description Data for a new account.
         */
        RegisterIn: {
            /**
             * Display Name
             * @description Display name in the UI and in notifications.
             * @example Anna
             */
            display_name: string;
            /**
             * Email
             * Format: email
             * @description Login name. Case is ignored.
             * @example anna@example.org
             */
            email: string;
            /**
             * Password
             * @description At least 8 characters. Only stored as an Argon2id hash (Q-03).
             * @example correct-horse-battery
             */
            password: string;
        };
        /**
         * UserOut
         * @description Account as the frontend sees it, without the password hash.
         */
        UserOut: {
            /**
             * Created At
             * Format: date-time
             * @description Account creation time (UTC).
             */
            created_at: string;
            /**
             * Display Name
             * @description Display name.
             */
            display_name: string;
            /**
             * Email
             * @description Login name, lowercased.
             */
            email: string;
            /**
             * Id
             * Format: uuid
             * @description Account ID (UUIDv7).
             */
            id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * ValidationIssue
         * @description One invalid field of a request.
         */
        ValidationIssue: {
            /** Loc */
            loc: string[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authDeleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    authLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    authLogoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    authMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    authRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listGifts: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_GiftOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createGift: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GiftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getGift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateGift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GiftIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GiftOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteGift: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthLive: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    healthReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    listOccasionTypes: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OccasionTypeOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOccasionType: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occasion_type_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccasionTypeOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listOccasions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_OccasionOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createOccasion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccasionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccasionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getOccasion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occasion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccasionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updateOccasion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occasion_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OccasionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OccasionOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteOccasion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occasion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listPeople: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_PersonOut_"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createPerson: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getPerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    updatePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonOut"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deletePerson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Problem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
