// VitePress site for the code reference. The pages under backend/ (Sphinx) and
// frontend/ (TypeDoc) are generated by `mise run apidocs` and not committed;
// reference/ includes the generated documents from docs/generated/.
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { defineConfig, type DefaultTheme } from 'vitepress';

const root = new URL('../', import.meta.url);

/** Sphinx writes one page per module (`giftmanager.core.auth.md`); group them by layer. */
function backendSidebar(): DefaultTheme.SidebarItem[] {
  const dir = new URL('backend/', root);
  if (!existsSync(dir)) return [];
  const modules = readdirSync(dir)
    .filter((f) => f.startsWith('giftmanager') && f.endsWith('.md'))
    .map((f) => f.slice(0, -'.md'.length))
    .sort();
  const isPackage = (name: string) => modules.some((m) => m.startsWith(`${name}.`));
  const groups = new Map<string, DefaultTheme.SidebarItem[]>();
  for (const name of modules) {
    // giftmanager.core.auth → group "core", text "auth"; giftmanager.main → group "giftmanager".
    const [, first, ...rest] = name.split('.');
    const group = first && isPackage(`giftmanager.${first}`) ? first : 'giftmanager';
    const text = group === 'giftmanager' ? (first ?? 'overview') : rest.join('.') || 'overview';
    groups.set(group, [...(groups.get(group) ?? []), { text, link: `/backend/${name}` }]);
  }
  return [...groups].map(([text, items]) => ({ text, items, collapsed: text !== 'giftmanager' }));
}

/** typedoc-vitepress-theme writes the sidebar next to the pages. */
function frontendSidebar(): DefaultTheme.SidebarItem[] {
  const file = new URL('frontend/typedoc-sidebar.json', root);
  return existsSync(file) ? JSON.parse(readFileSync(file, 'utf8')) : [];
}

export default defineConfig({
  title: 'Geschenke-Manager',
  description: 'Code reference of the Geschenke-Manager backend and frontend',
  // GitHub Pages serves the site under /isefgm/; locally it lives at the root.
  base: process.env.DOCS_BASE ?? '/',
  outDir: '../../apidocs',
  themeConfig: {
    nav: [
      { text: 'Backend', link: '/backend/' },
      { text: 'Frontend', link: '/frontend/' },
      { text: 'Reference', link: '/reference/api' }
    ],
    sidebar: {
      '/backend/': [{ text: 'Backend', link: '/backend/' }, ...backendSidebar()],
      '/frontend/': [{ text: 'Frontend', link: '/frontend/' }, ...frontendSidebar()],
      '/reference/': [
        {
          text: 'Generated from the code',
          items: [
            { text: 'API', link: '/reference/api' },
            { text: 'Database', link: '/reference/database' },
            { text: 'Configuration', link: '/reference/configuration' },
            { text: 'Traceability', link: '/reference/traceability' }
          ]
        }
      ]
    },
    outline: [2, 3],
    search: { provider: 'local' },
    socialLinks: [{ icon: 'github', link: 'https://github.com/julianammann/isefgm' }]
  }
});
