from collections.abc import AsyncIterator, Iterator
from datetime import UTC, datetime, timedelta
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from httpx import ASGITransport, AsyncClient
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine
from testcontainers.postgres import PostgresContainer

from giftmanager.core.clock import get_clock
from giftmanager.core.db import get_session
from giftmanager.main import app


@pytest.fixture(scope="session")
def database_url() -> Iterator[str]:
    with PostgresContainer("docker.io/library/postgres:17-alpine", driver="asyncpg") as pg:
        url = pg.get_connection_url()
        cfg = Config("alembic.ini")
        cfg.set_main_option("sqlalchemy.url", url)
        command.upgrade(cfg, "head")
        yield url


@pytest.fixture
async def session(database_url: str) -> AsyncIterator[AsyncSession]:
    engine = create_async_engine(database_url)
    async with engine.connect() as conn:
        trans = await conn.begin()
        maker = async_sessionmaker(
            conn, expire_on_commit=False, join_transaction_mode="create_savepoint"
        )
        async with maker() as s:
            yield s
        await trans.rollback()
    await engine.dispose()


@pytest.fixture
async def client(session: AsyncSession) -> AsyncIterator[AsyncClient]:
    async def _override() -> AsyncIterator[AsyncSession]:
        yield session

    app.dependency_overrides[get_session] = _override
    async with AsyncClient(transport=ASGITransport(app=app), base_url="http://test") as client:
        yield client
    app.dependency_overrides.clear()


class FixedClock:
    """Pinned `now` for the app; a test moves it forward with `advance`."""

    def __init__(self, now: datetime) -> None:
        self.current = now

    def now(self) -> datetime:
        return self.current

    def advance(self, delta: timedelta) -> None:
        self.current += delta


@pytest.fixture
def clock() -> Iterator[FixedClock]:
    fixed = FixedClock(datetime(2026, 1, 1, 12, 0, tzinfo=UTC))
    app.dependency_overrides[get_clock] = lambda: fixed
    yield fixed
    app.dependency_overrides.pop(get_clock, None)


# --- Requirement traceability (QZ-01, Q-09) -----------------------------------
# Tests declare the MS 1 requirements they cover: @pytest.mark.requirement("F-01", "Q-03").
# After a full run the matrix "requirement -> test -> outcome" is written to
# docs/generated/traceability.md; it is part of the MS 4 test report.
# Partial runs (-k, a single file) overwrite it with a partial matrix, so
# regenerate with a full `mise run test` before committing. See docs/dokumentation.md.

TRACEABILITY_OUT = Path(__file__).resolve().parents[2] / "docs" / "generated"
_requirements: dict[str, list[str]] = {}  # nodeid -> requirement ids
_outcomes: dict[str, str] = {}  # nodeid -> passed | failed | skipped


def pytest_collection_finish(session: pytest.Session) -> None:
    for item in session.items:
        ids = {str(rid) for mark in item.iter_markers("requirement") for rid in mark.args}
        _requirements[item.nodeid] = sorted(ids)


def pytest_runtest_logreport(report: pytest.TestReport) -> None:
    # Setup/teardown failures count too; a passed setup does not.
    if report.when == "call" or report.outcome != "passed":
        _outcomes[report.nodeid] = report.outcome


def pytest_sessionfinish(session: pytest.Session) -> None:
    if session.config.getoption("collectonly") or not _outcomes:
        return
    by_requirement: dict[str, list[str]] = {}
    unmapped: list[str] = []
    for nodeid, ids in _requirements.items():
        if not ids:
            unmapped.append(nodeid)
        for rid in ids:
            by_requirement.setdefault(rid, []).append(nodeid)

    lines = [
        "<!-- Generated by pytest (tests/conftest.py). Do not edit by hand. -->",
        "",
        "# Traceability: requirement ↔ test",
        "",
        "Requirement IDs from `docs/ms1_projektkonfiguration.md`. "
        + "Outcome of the last full test run.",
        "",
        "| Requirement | Test | Outcome |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| {rid} | `{nodeid}` | {_outcomes.get(nodeid, 'not run')} |"
        for rid in sorted(by_requirement)
        for nodeid in by_requirement[rid]
    )
    if unmapped:
        lines += ["", "## Tests without a requirement", ""]
        lines += [f"- `{nodeid}`" for nodeid in sorted(unmapped)]
    TRACEABILITY_OUT.mkdir(parents=True, exist_ok=True)
    (TRACEABILITY_OUT / "traceability.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )
