"""create gift

Revision ID: 6a6e7d90cec7
Revises: 393161257686
Create Date: 2026-10-08 14:54:45.564980

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6a6e7d90cec7"
down_revision: str | Sequence[str] | None = "393161257686"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gift",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key, UUIDv7."),
        sa.Column(
            "owner_id",
            sa.Uuid(),
            nullable=False,
            comment="Account the gift idea belongs to. Deleted together with the account.",
        ),
        sa.Column(
            "title",
            sa.String(length=200),
            nullable=False,
            comment="Short title, the only required field for quick capture.",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Free-text description. Optional."
        ),
        sa.Column(
            "price_from",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Lower end of the price range in `currency`. Optional.",
        ),
        sa.Column(
            "price_to",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Upper end of the price range in `currency`. Optional.",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="EUR",
            nullable=False,
            comment="ISO 4217 code of the price range currency, e.g. EUR.",
        ),
        sa.Column(
            "category",
            sa.Enum(
                "books",
                "games",
                "experience",
                "clothing",
                "tech",
                "food",
                "home",
                "voucher",
                "other",
                name="gift_category",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="other",
            nullable=False,
            comment="Kind of gift, feature for suggestions (F-16). `other` when not chosen.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation time (UTC), set by the database (Q-08).",
        ),
        sa.CheckConstraint("price_from <= price_to", name=op.f("ck_gift_price_range_ordered")),
        sa.CheckConstraint(
            "price_from >= 0 AND price_to >= 0", name=op.f("ck_gift_price_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user_account.id"],
            name=op.f("fk_gift_owner_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gift")),
        comment="Gift idea of an account (F-05): the reusable content of an idea. Visible only to its owner (Q-01); deleted together with the account (F-17).",
    )
    op.create_index("ix_gift_owner_id_created_at", "gift", ["owner_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_gift_owner_id_created_at", table_name="gift")
    op.drop_table("gift")
    # ### end Alembic commands ###
