"""create person_occasion

Revision ID: cbd3c5c4acbd
Revises: f1f09ac5f72a
Create Date: 2026-10-08 18:19:13.275125

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbd3c5c4acbd"
down_revision: str | Sequence[str] | None = "f1f09ac5f72a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_occasion",
        sa.Column(
            "person_id",
            sa.Uuid(),
            nullable=False,
            comment="Person the occasion concerns. Deleting the person deletes the link.",
        ),
        sa.Column(
            "occasion_id",
            sa.Uuid(),
            nullable=False,
            comment="Occasion. Deleting it deletes the link.",
        ),
        sa.ForeignKeyConstraint(
            ["occasion_id"],
            ["occasion.id"],
            name=op.f("fk_person_occasion_occasion_id_occasion"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_person_occasion_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("person_id", "occasion_id", name=op.f("pk_person_occasion")),
        comment="People an occasion concerns (F-04), n:m. Deleting the person or the occasion removes only the link.",
    )
    op.create_index(
        op.f("ix_person_occasion_occasion_id"), "person_occasion", ["occasion_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_person_occasion_occasion_id"), table_name="person_occasion")
    op.drop_table("person_occasion")
    # ### end Alembic commands ###
