"""create gift_person and gift_occasion

Revision ID: f1f09ac5f72a
Revises: 6a6e7d90cec7
Create Date: 2026-10-08 16:10:01.435578

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f1f09ac5f72a"
down_revision: str | Sequence[str] | None = "6a6e7d90cec7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "gift_person",
        sa.Column(
            "gift_id", sa.Uuid(), nullable=False, comment="Gift idea. Deleting it deletes the link."
        ),
        sa.Column(
            "person_id",
            sa.Uuid(),
            nullable=False,
            comment="Possible recipient. Deleting the person deletes the link.",
        ),
        sa.ForeignKeyConstraint(
            ["gift_id"], ["gift.id"], name=op.f("fk_gift_person_gift_id_gift"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
            name=op.f("fk_gift_person_person_id_person"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("gift_id", "person_id", name=op.f("pk_gift_person")),
        comment="Possible recipients of a gift idea (F-04), n:m. Deleting the idea or the person removes only the link. Actual recipients belong to a gifting (F-06).",
    )
    op.create_index(op.f("ix_gift_person_person_id"), "gift_person", ["person_id"], unique=False)
    op.create_table(
        "gift_occasion",
        sa.Column(
            "gift_id", sa.Uuid(), nullable=False, comment="Gift idea. Deleting it deletes the link."
        ),
        sa.Column(
            "occasion_id",
            sa.Uuid(),
            nullable=False,
            comment="Possible occasion. Deleting the occasion deletes the link.",
        ),
        sa.ForeignKeyConstraint(
            ["gift_id"], ["gift.id"], name=op.f("fk_gift_occasion_gift_id_gift"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["occasion_id"],
            ["occasion.id"],
            name=op.f("fk_gift_occasion_occasion_id_occasion"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("gift_id", "occasion_id", name=op.f("pk_gift_occasion")),
        comment="Possible occasions of a gift idea (F-04), n:m. Deleting the idea or the occasion removes only the link. The concrete occasion belongs to a gifting (F-06).",
    )
    op.create_index(
        op.f("ix_gift_occasion_occasion_id"), "gift_occasion", ["occasion_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_gift_occasion_occasion_id"), table_name="gift_occasion")
    op.drop_table("gift_occasion")
    op.drop_index(op.f("ix_gift_person_person_id"), table_name="gift_person")
    op.drop_table("gift_person")
    # ### end Alembic commands ###
