"""create user account and session

Revision ID: 8c4f215ecfae
Revises:
Create Date: 2026-09-22 09:53:01.782668

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c4f215ecfae"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_account",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key, UUIDv7."),
        sa.Column(
            "email",
            sa.String(length=320),
            nullable=False,
            comment="Login name. Stored lowercased and unique.",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="Argon2id hash of the password (Q-03). The password itself is never stored.",
        ),
        sa.Column(
            "display_name",
            sa.String(length=100),
            nullable=False,
            comment="Display name in the UI and in notifications.",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "deleted",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=16,
            ),
            server_default="active",
            nullable=False,
            comment="`active` or `deleted`. `deleted` only marks an account while it is being deleted.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation time (UTC), set by the database (Q-08).",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_account")),
        sa.UniqueConstraint("email", name=op.f("uq_user_account_email")),
        comment="User account (F-01). Every domain table belongs to exactly one account via "
        "owner_id; deleting the account deletes all of its data (F-17).",
    )
    op.create_table(
        "user_session",
        sa.Column("id", sa.Uuid(), nullable=False, comment="Primary key, UUIDv7."),
        sa.Column(
            "user_id",
            sa.Uuid(),
            nullable=False,
            comment="Account the session belongs to. Deleted together with the account.",
        ),
        sa.Column(
            "token_hash",
            sa.String(length=64),
            nullable=False,
            comment="SHA-256 of the cookie token. Only the browser knows the token itself.",
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Expiry time (UTC). The session is rejected afterwards.",
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Last use (UTC), updated at most every five minutes.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Creation time (UTC), set by the database (Q-08).",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_account.id"],
            name=op.f("fk_user_session_user_id_user_account"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_session_token_hash")),
        comment="Server-side session. One cookie token maps to exactly "
        "one row; logging out deletes the row.",
    )
    op.create_index(op.f("ix_user_session_user_id"), "user_session", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_session_user_id"), table_name="user_session")
    op.drop_table("user_session")
    op.drop_table("user_account")
    # ### end Alembic commands ###
